### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by hubutui** [loli/medpy#89]
Hi, I'm trying to package medpy for ArchLinux. After building medpy, I run `PYTHONPATH="${PWD}/build/lib.linux-x86_64-3.7" nosetests -v`, and here is the log.
```
==> Starting check()...
Failure: ModuleNotFoundError (No module named 'medpy.graphcut.maxflow') ... ERROR
Failure: ModuleNotFoundError (No module named 'medpy.graphcut.maxflow') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'medpy.graphcut.maxflow')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/build/python-medpy/src/medpy-0.4.0/medpy/graphcut/__init__.py", line 200, in <module>
    from .maxflow import GraphDouble, GraphFloat, GraphInt # this always triggers an error in Eclipse, but is right
ModuleNotFoundError: No module named 'medpy.graphcut.maxflow'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'medpy.graphcut.maxflow')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/build/python-medpy/src/medpy-0.4.0/tests/graphcut_/__init__.py", line 2, in <module>
    from .graph import TestGraph
  File "/build/python-medpy/src/medpy-0.4.0/tests/graphcut_/graph.py", line 19, in <module>
    from medpy.graphcut import GCGraph
  File "/build/python-medpy/src/medpy-0.4.0/medpy/graphcut/__init__.py", line 200, in <module>
    from .maxflow import GraphDouble, GraphFloat, GraphInt # this always triggers an error in Eclipse, but is right
ModuleNotFoundError: No module named 'medpy.graphcut.maxflow'

----------------------------------------------------------------------
Ran 2 tests in 0.382s

FAILED (errors=2)
```

Actually, if I skip the check, I could still import `medpy.graphcut.maxflow` without error. I'm not sure why the test failed.

**Comment by loli** [comment]
Thanks for pointing this out! It might have something to do with the relative import and conflicting names... I will look into this for the next release.

**Comment by EricKani** [comment]
Hello @loli ~

Has this issue been solved~ I encounter this error also, even after I install Boost.python and reinstall this package... 

Thanks,
Best,
eric

**Comment by loli** [comment]
The graphcut plugin is notoriously tricky. If you don't need it, you can
safely ignore this.

**Comment by EricKani** [comment]
Hi～

Sorry I am not very good on English… Do you mean the integration of graphcut plugin is a hard problem for most people？But I really need this plugin…Do you have any other solutions or suggestions… Thank you very much！

Best，
eric




| |
信工 刘蓬博
邮箱：pengbo18555@163.com
|

签名由 网易邮箱大师 定制

On 03/28/2020 00:56, Oskar M. wrote:

The graphcut plugin is notoriously tricky. If you don't need it, you can
safely ignore this.

**Comment by YunxinZhong** [comment]
The follow link solve this issue. Install Boost.python and modify setup.py.

https://pengyizhang.github.io/2020/04/05/medpyinstall/

**Comment by EricKani** [comment]
> The follow link solve this issue. Install Boost.python and modify setup.py.
> 
> https://pengyizhang.github.io/2020/04/05/medpyinstall/

Thanks for your reply~ But my server is Linux system. A little bit not suitable for my scene.

**Comment by jjerphan** [comment]
Hello,

I also get the same problem on Fedora 32 using:
 - python 3.8 (from package manager)
 - python 3.6, 3.7 from anaconda

be it by installing it from source or via pypi. libboost-python is installed on my machine aswell.

#87 and #81 are related an relevant issues.

**Comment by loli** [comment]
Should now work for most ditros: see also http://loli.github.io/medpy/installation/graphcutsupport.html

And, in case it doesn't, can be installed pre-packed from conda-forge.
